### ISSUE TITLE
Getting error after installation 

### ISSUE THREAD

**Issue by sanjeetbisht** [moseseth/tiktok-scraper#3]
Hello, whatever I run and do I'm getting this error. 

{"success":false,"message":"The current node list is empty."}

**Comment by moseseth** [comment]
I have not updated the codebase for a while, and perhaps the DOM structure of tiktok has been updated as well. 

Will look into it sometime, or better you can fix it :) 

Cheers!

**Comment by umeshdepale** [comment]
@moseseth how to use this

**Comment by moseseth** [comment]
> @moseseth Any updates?
> Getting **The current node list is empty.** here aswell.

@ggloveswp : on the horizon, am back to coding again, so will have a look & update the status!

**Comment by ggloveswp** [comment]
Thanks. Stay healthy.

**Comment by moseseth** [comment]
> Thanks. Stay healthy.

Thanks @ggloveswp 
I have committed the first update now. For in the future, you can follow up this change log.
Moreover, after this final release of 2.0, all additional work will be in a different release branch as well. Enjoy & It is open for contribution of ideas in the future. 

**https://github.com/moseseth/tiktok-scraper/blob/master/CHANGELOG.md**

**Comment by moseseth** [comment]
> @moseseth how to use this

@umeshdepale : Please look into the readme file. Must be descriptive if you have already worked with lumen/laravel framework. If not, reach me can help! 
@sanjeetbisht thank you for reporting the issue and it is being resolved. Read the previous thread.
